opt_in_rules:
#  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
#  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - extension_access_modifier
  - fallthrough
#  - fatal_error_message
#  - file_header
#  - file_name
#  - first_where
  - identical_operands
  - implicit_return
  - joined_default_parameter
#  - let_var_whitespace
#  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - nimble_operator
#  - number_separator
#  - object_literal
#  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
#  - sorted_first_last
  - sorted_imports
  - static_operator
#  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
#  - vertical_whitespace_opening_braces
#  - xct_specific_matcher
  - yoda_condition
disabled_rules:
  - class_delegate_protocol
  - identifier_name
  - large_tuple
  - multiple_closures_with_trailing_closure
  - todo
  - trailing_whitespace
  - weak_delegate
  - unused_optional_binding
  - unused_closure_parameter
cyclomatic_complexity:
  warning: 14
function_parameter_count:
  warning: 10
function_body_length: 100
line_length: 700
file_length: 600
type_body_length: 400
type_name:
  min_length: 3
  max_length:
    warning: 70
    error: 70
trailing_comma:
  mandatory_comma: false
excluded:
  - Playgrounds
  - Submodules
